// Alphabetical, with the catch-all last.
export const BREEDS = [
  'Akita',
  'Alaskan Malamute',
  'Australian Cattle Dog (Blue Heeler)',
  'Australian Shepherd',
  'Basset Hound',
  'Beagle',
  'Bernese Mountain Dog',
  'Bloodhound',
  'Border Collie',
  'Boston Terrier',
  'Boxer',
  'Bulldog',
  'Cavalier King Charles Spaniel',
  'Chihuahua',
  'Chow Chow',
  'Cocker Spaniel',
  'Corgi',
  'Dachshund',
  'Dalmatian',
  'Doberman Pinscher',
  'French Bulldog',
  'German Shepherd',
  'Golden Retriever',
  'Goldendoodle',
  'Great Dane',
  'Greyhound',
  'Jack Russell Terrier',
  'Labradoodle',
  'Labrador Retriever',
  'Maltese',
  'Mastiff',
  'Newfoundland',
  'Pomeranian',
  'Poodle',
  'Pug',
  'Rottweiler',
  'Saint Bernard',
  'Samoyed',
  'Shetland Sheepdog',
  'Shiba Inu',
  'Shih Tzu',
  'Siberian Husky',
  'Staffordshire / Pit Bull Terrier',
  'Vizsla',
  'Weimaraner',
  'Whippet',
  'Yorkshire Terrier',
  'Mixed / Other',
];

/** Sensible default breed for a new pet (catch-all). */
export const DEFAULT_BREED = 'Mixed / Other';

/** Preset temperament tags for the pet form — most common first. */
export const TEMPERAMENTS = [
  // popular
  'friendly',
  'playful',
  'gentle',
  'energetic',
  'calm',
  'affectionate',
  'smart',
  'good-with-dogs',
  'good-with-kids',
  'snuggly',
  'goofy',
  'loyal',
  // the rest
  'shy',
  'high-energy',
  'couch-potato',
  'protective',
  'curious',
  'stubborn',
  'independent',
  'anxious',
  'leash-reactive',
  'vocal',
  'quiet',
  'food-motivated',
  'ball-obsessed',
  'water-lover',
  'adventurous',
  'good-with-cats',
  'puppy',
  'senior',
  'rescue',
];
